services:
  - type: web
    name: auctora
    env: static
    buildCommand: |
      cd client
      npm install
      npm run build
    staticPublishPath: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_SUPABASE_URL
        value: https://your-supabase-url.supabase.co
      - key: REACT_APP_SUPABASE_ANON_KEY
        value: your-anon-key
