INSERT INTO "Artwork"(title, description, image_url, price, category, medium, dimensions, year, artist_name, is_sold)
VALUES
(
    'Highest Peak of the World: Everest',
    'A stunning oil painting of Mount Everest, capturing the grandeur and icy stillness of the world’s tallest peak. The artist skillfully portrays the snow-covered ridges, the crisp atmosphere, and the majesty of the Himalayan landscape.',   'https://d3rf6j5nx5r04a.cloudfront.net/3dmSHyukcsyivtAkeNfe778fvzQ=/750x562/filters:quality(95)/product/f/e/2c9ea3f3097f41848a7202826cfb3f52_opt.jpg',
    4800.00,
    'Landscape Painting',
    'Oil on Canvas',
    '30x24 inches',
    2025,
    'KP Sharma Oil',
    FALSE
),
(
    'Gautam Buddha – The Enlightened One',
    'A modern acrylic painting by Vishal Gurjar depicting Lord Gautam Buddha in a meditative pose, capturing the peaceful serenity and enlightenment associated with Buddhist spirituality. The artwork blends vibrant contemporary colors with traditional religious themes.',
    'https://images.fineartamerica.com/images/artworkimages/mediumlarge/2/gautam-buddha-the-enlightened-one-vishal-gurjar.jpg',
    350.00,
    'Modern Religious Art',
    'Acrylic on Canvas',
    '36x24 inches',
    2019,
    'Vishal Gurjar',
    FALSE
),
(
    'Buddhist Thangka from Nepal',
    'A traditional Buddhist Thangka painting from Nepal, depicting a vibrant, detailed portrayal of a deity or spiritual figure.',
    'https://c8.alamy.com/comp/CP95NH/buddhist-painting-thangka-from-nepal-CP95NH.jpg',
    700.00,
    'Religious Art',
    'Acrylic on Canvas',
    '24x36 inches',
    2023,
    'Tshering Dorje Sherpa',
    FALSE
),
(
    'Pashupatinath Temple at Sunset',
    'A oil painting of the historic Pashupatinath Temple in Kathmandu, Nepal. The artwork captures the temple’s grand architecture under a vibrant sunset sky, showcasing rich cultural heritage with spiritual ambiance.',
    'https://numpaint.com/wp-content/uploads/2022/02/Shri-Pashupatinath-Temple-kathmandu-paint-by-number.jpg',
    800.00,
    'Cultural Heritage Art',
    'Oil Painting',
    '30x40 inches',
    2024,
    'Rijen Singh',
    FALSE
),
(
    'Abstract Climbers on a Snowy Mountain',
    'A textured abstract painting showing two mountaineers climbing a snow-covered slope, inspired by high-altitude expeditions on Mount Everest. This painting uses a rich palette of blues and whites with dramatic sky tones, evoking both struggle and beauty.',
    'https://images.fineartamerica.com/images/artworkimages/mediumlarge/3/watercolor-of-sherpas-on-himalayan-mountain-near-everest-steve-estvanik.jpg',
    950.00,
    'Adventure Art',
    'Abstract',
    '24x36 inches',
    2024,
    'Steve Estvanik',
    FALSE
),
(
    'Kumari – Living Goddess of Nepal',
    'A painting of Kumari, the living goddess in Nepalese tradition, adorned in rich traditional attire and intricate face makeup. The Kumari is a prepubescent girl worshipped as the bodily incarnation of the divine feminine energy in Hindu and Buddhist cultures of Nepal.',
    'https://www.remotelands.com/travelogues/app/uploads/2019/10/Kumaris-2.jpg',
    1000.00,
    'Cultural Photography',
    'Portrait',
    '1920x1280 pixels',
    2019,
    'Kuma Sagar',
    FALSE
),
(
    'Lord Shiva – The Destroyer',
    'A spray painting of Lord Shiva, known as the Destroyer in Hindu mythology. The artwork features a highly detailed depiction of Shiva with iconic elements like crescent moon, flowing hair, and Trishul (trident), symbolizing power, destruction, and transcendence. The abstract background enhances the divine and intense energy of the piece.',
    'https://i.etsystatic.com/22448967/r/il/9be44a/3139768049/il_fullxfull.3139768049_a2zt.jpg',
    800.00,
    'Mythological Art',
    'Oil Painting',
    '1920x1280 pixels',
    2021,
    'Yash Chitrakar',
    FALSE
),
(
    'Himalayan Serenity – Hand-Painted Mountain Landscape',
    'A captivating oil painting depicting the majestic Himalayan mountain range, showcasing snow-capped peaks, lush valleys, and traditional Nepali village life. This artwork reflects the serene beauty and cultural richness of Nepal’s mountainous regions.',
    'https://handmadeexpo.com/pics/product/29051.jpg',
    360.00,
    'Landscape Art',
    'Oil on Cotton Canvas',
    '122x46 cm',
    2023,
    'Rajesh Dai',
    FALSE
),
(
    'Mystic Forest River – Oil Painting Landscape',
    'A tranquil oil painting of a forest landscape with a flowing river reflecting the soft hues of the sky. The warm autumn tones, misty atmosphere, and serene water create a peaceful, dreamlike setting that evokes calm and introspection.',
    'https://webneel.com/daily/sites/default/files/images/daily/10-2018/12-landscape-artwork-oil-painting-scenery-arteet.jpg',
    275.00,
    'Landscape Art',
    'Oil on Canvas',
    '90x60 cm',
    2018,
    'Arteet Studio',
    FALSE
),
(
    'Fragmented Identity – Abstract Portrait Painting',
    'A powerful abstract oil portrait depicting a person with glasses, painted with expressive brushstrokes and intense color contrasts. The fragmented composition explores emotion and identity through texture and modern figurative technique.',
    'https://mymodernmet.com/wp/wp-content/uploads/2019/12/oil-paintings-jacob-dhein-12.jpg',
    600.00,
    'Abstract Figurative',
    'Oil on Canvas',
    '70x50 cm',
    2019,
    'Jacob Dhein',
    FALSE
),
(
    'Vision Unbound – Abstract Eye in Motion',
    'An expressive abstract oil painting of a human eye, bursting with vivid color and texture. Swirling strokes of blue, orange, and crimson radiate from the iris, evoking emotion, perception, and raw energy in a bold contemporary style.',
    'https://static.vecteezy.com/system/resources/previews/022/740/494/large_2x/oil-painting-conceptual-abstract-picture-of-the-eye-oil-painting-in-colorful-colors-generate-ai-free-photo.jpg',
    625.00,
    'Abstract Expressionism',
    'Oil on Canvas',
    '70x50 cm',
    2023,
    'Ahasanara Akter',
    FALSE
),
(
    'The Fallen Angels',
    'A powerful Romantic oil painting by Alexandre Cabanel depicting the biblical fall of Lucifer and the rebel angels, as divine forces cast them out of Heaven. Known for its emotional intensity, celestial contrasts, and masterful detail.',
    'https://artincontext.org/wp-content/uploads/2022/04/Famous-Renaissance-Painting.jpg',
    740.00,
    'Romantic Academic',
    'Oil on canvas',
    '225x307 cm',
    1847,
    'Alexandre Cabanel',
    FALSE
),
(
    'Sunset Serenity – Lakeside Landscape',
    'A tranquil oil painting depicting a serene lakeside scene. The artwork features warm hues reflecting off the water, surrounded by lush trees and gentle hills, capturing the peaceful essence of nature.',
    'https://webneel.com/daily/sites/default/files/images/daily/10-2018/18-landscape-oil-painting-arteet.jpg',
    300.00,
    'Landscape Art',
    'Oil on Canvas',
    '80x60 cm',
    2018,
    'Arteet Studio',
    FALSE
),
(
    'Mona Lisa',
    'The Mona Lisa embodies the artistic genius of Leonardo da Vinci. Created in the early 16th century, its enigmatic smile and groundbreaking techniques in portraiture have made it a subject of fascination for centuries.',
    'https://anitalouiseart.com/wp-content/uploads/2023/06/Mona-Lisa.jpeg?ezimgfmt=ng:webp/ngcb11',
    320.00,
    'Renaissance',
    'Oil on Poplar Panel',
    '30x20 inches',
    2023,
    'Leonardo da Vinci ',
    FALSE
),
(
    'The Kiss',
    'A symbol of love and intimacy, “The Kiss” is celebrated for its sumptuous decorative patterns and universal theme. Klimt’s use of gold leaf adds a mythical quality to the piece, elevating a simple embrace of the realm of the divine.',
    'https://anitalouiseart.com/wp-content/uploads/2023/04/22The-Kiss22-by-Gustav-Klimt-1908-768x768.jpeg?ezimgfmt=ng:webp/ngcb11',
    400.00,
    'Art Nouveau',
    'Oil and Gold Leaf on Canvas',
    '30x30 inches',
    2023,
    'Gustav Klimt',
    FALSE
),
(
    'Girl with a Pearl Earring – ',
    'Often referred to as the “Dutch Mona Lisa,” this captivating portrait is famous for its enigmatic expression and exquisite detail, especially in the eponymous pearl earring. Vermeer’s mastery of light elevates the painting into a timeless icon.',
    'https://anitalouiseart.com/wp-content/uploads/2022/10/Girl-With-A-Pearl-Earring-By-Johannes-Vermeer-768x909.jpeg?ezimgfmt=ng:webp/ngcb11',
    800.00,
    'Baroque',
    'Oil on Canvas',
    '17.5x15 inches',
    1665,
    'Johannes Vermeer',
    FALSE
),
(
    'The Birth of Venus',
    'A masterpiece of the Italian Renaissance, “The Birth of Venus” epitomizes beauty and grace. Depicting the goddess Venus emerging from the sea, it has become a symbol of idealized femininity and natural beauty.',
    'https://anitalouiseart.com/wp-content/uploads/2022/12/The-Birth-of-Venus-1-768x483.jpeg?ezimgfmt=ng:webp/ngcb11',
    290.00,
    'Renaissance',
    'Tempera on Canvas',
    '172.5x278.5 cm',
    1484,
    'Sandro Botticelli',
    FALSE
),
(
    'Las Meninas',
    'Velázquez’s complex and mysterious composition is a masterclass in perspective and a commentary on the act of painting itself. Its influence can be seen in the works of numerous artists who followed, including Pablo Picasso and Salvador Dalí.',
    'https://anitalouiseart.com/wp-content/uploads/2022/06/Las-Meninas.jpeg?ezimgfmt=ng:webp/ngcb11',
    349.99,
    'Baroque',
    'Oil on Canvas',
    '125.2x108.7 inches',
    1656,
    'Diego Velázquez',
    FALSE
),
(
'Bombing of Guernica',
    'A visceral reaction to the bombing of the Basque town of Guernica during the Spanish Civil War, Picasso’s painting serves as a powerful anti-war statement. Its cubist shapes and monochromatic palette convey the horrors of conflict.',
    'https://www.bing.com/images/search?view=detailV2&ccid=Yy9jbXOQ&id=C592AC4965F76905A29BC804065F2A6907F0888F&thid=OIP.Yy9jbXOQClyaiG-05DwWVAHaES&mediaurl=https%3A%2F%2Fc8.alamy.com%2Fcomp%2F2H1W2P7%2Fguernica-spain-april-09-2018-a-tiled-wall-in-gernika-reminds-of-the-bombing-during-the-spanish-civil-warpainting-1937-by-pablo-picasso-2H1W2P7.jpg&cdnurl=https%3A%2F%2Fth.bing.com%2Fth%2Fid%2FR.632f636d73900a5c9a886fb4e43c1654%3Frik%3Dj4jwB2kqXwYEyA%26pid%3DImgRaw%26r%3D0&exph=753&expw=1300&q=guernica+bombing+painting&simid=608030949222581951&form=IRPRST&ck=D98E46AFB919620DE7F53075B113CF5D&selectedindex=2&itb=0&cw=1431&ch=758&ajaxhist=0&ajaxserp=0&vt=0&sim=11',
    499.99,
    'Cubism',
    'Oil on Canvas',
    '11.5x25.6 feet',
    1937,
    'Pablo Picasso',
    FALSE
),
(
    'The Persistence of Memory',
    'Salvador Dalí’s surreal landscapes filled with melting clocks visually explore the complexities of time and the human psyche. It remains one of the most famous surrealist works ever created.',
    'https://anitalouiseart.com/wp-content/uploads/2022/06/The-Persistence-of-Memory-by-Salvador-Dali-768x402.jpeg?ezimgfmt=ng:webp/ngcb11',
    799.99,
    'Surrealism',
    'Oil on Canvas',
    '9.5x13 inches',
    1931,
    'Salvador Dalí',
    FALSE
),
(
    'The Night Watch (1642) – By Rembrandt van Rijn',
    'This monumental painting by Rembrandt is famous for its dramatic use of light and shadow and its revolutionary approach to portraiture. It showcases a group of city guards, immortalizing them in a composition teeming with life and movement.',
    'https://anitalouiseart.com/wp-content/uploads/2023/06/The-Night-Watch-1642-By-Rembrandt-van-Rijn-768x625.webp?ezimgfmt=ng:webp/ngcb11',
    1200.00,
    'Baroque Art',
    'Oil on Canvas',
    '363x437 cm',
    1642,
    'Rembrandt van Rijn',
    FALSE
),
(
    'The Last Supper (1495-1498) – By Leonardo da Vinci',
    'Another masterpiece from Leonardo da Vinci, “The Last Supper,” is famous for its architectural precision, emotional intensity, and portrayal of a significant moment in Christian narratives. Its deteriorating condition adds to its aura as a fading but undying beacon of art history.',
    'https://anitalouiseart.com/wp-content/uploads/2022/05/The-Last-Supper-768x384.jpeg?ezimgfmt=ng:webp/ngcb11',
    2500.00,
    'Renaissance Art',
    'Tempera on Gesso, Pitch, and Mastic',
    '460x880 cm',
    1498,
    'Leonardo da Vinci',
    FALSE
),
(
    'The Creation of Adam (1512)',
    'Part of the Sistine Chapel’s ceiling, this iconic work depicts the Biblical story of the creation of man. Michelangelo’s revolutionary technique and composition have made it one of the world’s most replicated and parodied images.',
    'https://anitalouiseart.com/wp-content/uploads/2023/04/The-Creation-of-Adam1512-By-Michelangelo-Buonarroti-768x593.jpeg?ezimgfmt=ng:webp/ngcb11',
    3000.00,
    'Renaissance Art',
    'Fresco',
    '280x570 cm',
    1512,
    'Michelangelo Buonarroti',
    FALSE
),
(
    'A Sunday Afternoon on the Island of La Grande Jatte',
    'A triumph of pointillism, this painting captures the leisurely life of Parisians in a local park. Seurat’s painstaking technique involved applying tiny dots of color, which, from a distance, blend to create a radiant atmosphere.',
    'https://anitalouiseart.com/wp-content/uploads/2023/09/A-Sunday-Afternoon-on-the-Island-of-La-Grande-Jatte-1886-By-Georges-Seurat-768x516.jpg?ezimgfmt=ng:webp/ngcb11',
    3500.00,
    'Post-Impressionism',
    'Oil on Canvas',
    '207.6 x 308 cm',
    1886,
    'Georges Seurat',
    FALSE
),
(
    'Impression, Sunrise',
    'Marking the birth of Impressionism, the name of this painting inspired the name of the entire movement. Monet’s focus on the effects of light on water resulted in a canvas that breaks traditional rules of composition.',
    'https://anitalouiseart.com/wp-content/uploads/2023/06/Impression-Sunrise-1872-By-Claude-Monet-768x597.jpeg?ezimgfmt=ng:webp/ngcb11',
    2000.00,
    'Impressionism',
    'Oil on Canvas',
    '48 x 63 cm',
    1872,
    'Claude Monet',
    FALSE
),
(
    'Wanderer above the Sea of Fog ',
    'An iconic painting of the Romantic period, it encapsulates the feeling of the sublime, facing the infinite and the unknown. The lone figure amid nature’s grandeur speaks to exploration and existential introspection themes.',
    'https://anitalouiseart.com/wp-content/uploads/2023/09/Wanderer-above-the-Sea-of-Fog-1818-By-Caspar-David-Friedrich-768x981.jpg?ezimgfmt=ng:webp/ngcb11',
    2500.00,
    'Romanticism',
    'Oil on Canvas',
    '94 x 74 cm',
    1818,
    'Caspar David Friedrich',
    FALSE
);


